bin/buildozer.js
lib/error.js

`buildozer js-concat`, `buildozer svg-sprite`, `buildozer clean` & `buildozer copy` commands were not executable or documented in the error report.

Add commands to bin file

---

lib/gulp/css.js
lib/gulp/image.js
lib/gulp/js.js

Only `buildozer watch` shouldn't return exit code 1 when a task fails.

Only use plumber on watch

---

gulpfile.js
lib/gulp/css.js
lib/gulp/image.js
lib/gulp/js.js

Sorry for the pull request spams.. :D
If you have functions with a few parameters it's more flexible to destruct them. This allows users to be flexible in which parameter they want to pass in.
Let's say you have this function
```javascript
// normal parameters
function jsConcat(src, dest, name, minified = true, browserSync = false) {
//...
}
// destructed parameters
function jsConcat({src, dest, name, minified = true, browserSync = false}) {
//...
}
```
If we use the normal parameters  I have to explicitly pass minified again even though there is a default value.
```javascript
jsConcat('src/path', 'dest/path', 'name', false, true);
```
I can omit the minified parameter as it has a default value. Also the readability is better as the parameters names are instantly visible
```javascript …
```

Converted long parameter function to destructed parameters object.

---

lib/gulp/js.js

CI tests were not enabled when https://github.com/Intracto/buildozer/pull/24 was merged, thus this issue was not found

Remove `eslint-disable-next-line max-params`

---

README.md

Browserslist is fully supported. Just added some documentation.
Closes #21

Add Browserslist documentation

---

gulpfile.js
lib/gulp/css.js
lib/gulp/js.js

This would allows user to use the context in for example a PostCSS config (#19).
```javascript
module.exports = (ctx) => {
return {
plugins: [
require('rfs')(),
require('postcss-inline-svg')(),
require('autoprefixer')(),
ctx.env === 'production' ? require('cssnano')() : false,
]
}
};
```
Thoughts?

Modify tasks to use process.env.NODE_ENV convention

---

lib/gulp/css.js
lib/gulp/image.js
lib/gulp/js.js

Fixes https://github.com/Intracto/buildozer/issues/22. The main tasks now return a promise of all subtasks instead of directly calling the callback function.

Use promises for callbacks

---

lib/gulp/image.js
lib/gulp/js.js
package-lock.json
package.json

This is actually also a fix for #22, but for the `js` and `img` tasks.
**Before**
- `js` & `img` duration times are incorrect
- `js` & `img` seemed to be finished before they are completed (`gulp-imagemin` outputs after `build` task)
```
[14:08:14] Working directory changed to ~/workspace/buildozer
[14:08:17] Using gulpfile ~/workspace/buildozer/gulpfile.js
[14:08:17] Starting 'build'...
[14:08:17] Starting 'clean'...
[14:08:17] Finished 'clean' after 7.52 ms
[14:08:17] Starting 'copy'...
Files copied:
- /Users/martijn.cuppens/workspace/buildozer-test/copy/file.txt to
/Users/martijn.cuppens/workspace/buildozer-test/dest/file.txt
[14:08:17] Finished 'copy' after 61 ms
[14:08:17] Starting 'css'...
[14:08:17] Starting 'js'...
[14:08:17] Starting 'img'...
[14:08:17] Finished 'js' after 92 ms …
```

Fix js & img tasks from logging being finished before actually being finished

---

lib/gulp/copy.js

Consider configured base path when copying files

---

gulpfile.js

Fixes a bug in the watch task that added the destination base path to the name of the file

Remove dest_base_path in watch task

---

gulpfile.js

Fix variable name

---

package-lock.json

`caniuse-lite` is a dependancy somewhere in the depstree and always shows the following error:
```
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
```
I fixed this by updating these dependencies:
`npm update --depth 10 caniuse-lite browserslist`

Fix outdated `caniuse-lite`

---

package-lock.json
package.json

Not used by the gulp scripts, only for testing scripts.

Move npm-run-all to dev dependencies

---

README.md
gulpfile.js
lib/gulp/css.js
package-lock.json
package.json
test/fail-stylelint/.stylelintrc
test/fail-stylelint/scss/main.scss
test/fail-tests.js
test/stylelint/.stylelintrc
test/stylelint/dest/css/main.css
test/stylelint/scss/main.scss

Enable CSS linting when when stylelint cosmiconfig is detected.
Also added a `fail-tests.js` file. These tests fail no error is triggered.
When `watch` is used, the css task is run when the stylelint config is adjusted.

Stylelint integration

---

gulpfile.js
lib/gulp/configs.js

The current implementation searches for config files everywhere (`node_modules` folder included). Also, we encountered some issues when the glob pattern is added at the beginning of the path.

Remove glob patterns from stylelint config

---

.github/workflows/linting.yml
package.json

Linting of the Buildozer package should only work on the latest LTS node version, we develop on latest LTS anyway.
This should fix this failed test: https://github.com/Intracto/buildozer/pull/111/checks?check_run_id=443391482

Split unit tests from linting

---

README.md
lib/.buildozerrc
lib/gulp/css.js
lib/gulp/image.js
package.json
test/config-search/nested/dest/css/main.css
test/css/.buildozerrc
test/css/dest/css/main.css
test/css/scss/main.css

In the config file, the `{png,jpg,jpeg,gif,svg}` patterns are seperated into multiple items in the array. This way, eg `.png` files won't be compiled when source `.svg` files are changed in the watch. Also, this makes it easier to add plugins to specific extensions.
Support for `.css` and `.sass` is also added. It looks a bit weird to have them under the `scss` key in the config, but this will soon change with https://github.com/Intracto/buildozer/issues/17.

Config rule per extension

---

lib/gulp/css.js
lib/gulp/sass.js
package-lock.json
package.json

Removal of `gulp-sass` which includes `node-sass` by default. `node-sass` is an unused package which needed to be built whenever npm i was executed for the first time or versions were switched. We do have more code to maintain with this change, but the drop in dependencies is worth it.

Remove `gulp-sass`

---

lib/gulp/configs.js

use process.env.INIT_CWD instead of process.env.PWD as this is set by NPM and Yarn regardless of the OS your are running.
fixes #174

fixes #174 use process.env.INIT_CWD

---

.github/workflows/test.yml
lib/gulp/sass.js
package-lock.json
package.json

This completely removes the 'fibers' package - which is not required for SASS to work.
The fibers package is not compatible with node 16, and also sometimes fails to work on node 10. It also requires stuff like node-gyp and build tools, which just makes it harder to install.
Because it doesn't have a lot of benefits and it is giving problems, I think it's better if this package is removed.
This MR also adds a test for node 16 to prove it works.
-----
To use this patch in your project already, see #287.

Make compatible with node 16 by removing fibers

---

.github/workflows/test.yml
lib/gulp/configs.js
lib/gulp/sass.js
package-lock.json
package.json

This PR is dependent on #281. That one should be merged first.
-----------
It looks like the config_search is currently not working at all, in the master (v1) branch.
This adds a more reliable way of searching for buildozer files and adding it to the gulp config.

Fix config search
